services:
  mav.api:
    image: ${DOCKER_REGISTRY-}mavapi
    build:
      context: .
      dockerfile: src/Mav.Api/Dockerfile
  mav.eventlistener:
    image: ${DOCKER_REGISTRY-}eventlistener
    build:
      context: .
      dockerfile: src/Mav.EventListener/Dockerfile
